---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [1]:

import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [2]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

In [3]:
df.iloc[-1, : ]

# Summer            3
Gold                8
Silver              5
Bronze              4
Total              17
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games             3
Gold.2              8
Silver.2            5
Bronze.2            4
Combined total     17
ID                ZZX
Name: Mixed team, dtype: object

In [4]:
df.columns

Index(['# Summer', 'Gold', 'Silver', 'Bronze', 'Total', '# Winter', 'Gold.1',
       'Silver.1', 'Bronze.1', 'Total.1', '# Games', 'Gold.2', 'Silver.2',
       'Bronze.2', 'Combined total', 'ID'],
      dtype='object')

In [5]:
df.index

Index(['Afghanistan', 'Algeria', 'Argentina', 'Armenia', 'Australasia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       ...
       'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Virgin Islands',
       'Yugoslavia', 'Independent Olympic Participants', 'Zambia', 'Zimbabwe',
       'Mixed team'],
      dtype='object', length=146)

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [6]:
type(df['Gold'].idxmax())

str

In [7]:
df['Gold'].idxmax()

'United States'

In [8]:
def answer_one():
    # df.loc[df['Gold'].idxmax()]    : return the entire row
    return df['Gold'].idxmax() # returns the row name
answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [9]:
def answer_two():
    return (df['Gold'] - df['Gold.1']).idxmax()

answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [10]:
df[(df['Gold.1'] > 0) & (df['Gold'] > 0)]

# Summer  Gold  Silver  Bronze  Total  # Winter  \
Australia                     25   139     152     177    468        18   
Austria                       26    18      33      35     86        22   
Belarus                        5    12      24      39     75         6   
Belgium                       25    37      52      53    142        20   
Bulgaria                      19    51      85      78    214        19   
Canada                        25    59      99     121    279        22   
China                          9   201     146     126    473        10   
Croatia                        6     6       7      10     23         7   
Czech Republic                 5    14      15      15     44         6   
Czechoslovakia                16    49      49      45    143        16   
Estonia                       11     9       9      15     33         9   
Finland                       24   101      84     117    302        22   
France                        27   202     223     246    671        22   
Germany                       15   174     182     217    573        11   
United Team of Germany         3    28      54      36    118         3   
East Germany                   5   153     129     127    409         6   
West Germany                   5    56      67      81    204         6   
Great Britain                 27   236     272     272    780        22   
Italy                         26   198     166     185    549        22   
Japan                         21   130     126     142    398        20   
Kazakhstan                     5    16      17      19     52         6   
South Korea                   16    81      82      80    243        17   
Netherlands                   25    77      85     104    266        20   
Norway                        24    56      49      43    148        22   
Poland                        20    64      82     125    271        22   
Russia                         5   132     121     142    395         6   
Soviet Union                   9   395     319     296   1010         9   
Unified Team                   1    45      38      29    112         1   
Slovakia                       5     7       9       8     24         6   
Slovenia                       6     4       6       9     19         7   
Spain                         22    37      59      35    131        19   
Sweden                        26   143     164     176    483        22   
Switzerland                   27    47      73      65    185        22   
Ukraine                        5    33      27      55    115         6   
United States                 26   976     757     666   2399        22   
Uzbekistan                     5     5       5      10     20         6   

                        Gold.1  Silver.1  Bronze.1  Total.1  # Games  Gold.2  \
Australia                    5         3         4       12       43     144   
Austria                     59        78        81      218       48      77   
Belarus                      6         4         5       15       11      18   
Belgium                      1         1         3        5       45      38   
Bulgaria                     1         2         3        6       38      52   
Canada                      62        56        52      170       47     121   
China                       12        22        19       53       19     213   
Croatia                      4         6         1       11       13      10   
Czech Republic               7         9         8       24       11      21   
Czechoslovakia               2         8        15       25       32      51   
Estonia                      4         2         1        7       20      13   
Finland                     42        62        57      161       46     143   
France                      31        31        47      109       49     233   
Germany                     78        78        53      209       26     252   
United Team of Germany       8         6        

In [11]:
def answer_three():
    GoldSW = df[(df['Gold.1'] > 0) & (df['Gold'] > 0)]
    
    return ((GoldSW['Gold'] - GoldSW['Gold.1'])/GoldSW['Gold.2']).idxmax()
    
answer_three()

'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [12]:
#Points = pd.Series({})

df['Points'] = df['Gold.2'] * 3 + df['Silver.2'] * 2 + df['Bronze.2'] * 1

In [13]:
type(df['Points'])

pandas.core.series.Series

In [14]:
def answer_four():
    df['Points'] = df['Gold.2'] * 3 + df['Silver.2'] * 2 + df['Bronze.2'] * 1
    return df['Points']

answer_four()

Afghanistan                            2
Algeria                               27
Argentina                            130
Armenia                               16
Australasia                           22
Australia                            923
Austria                              569
Azerbaijan                            43
Bahamas                               24
Bahrain                                1
Barbados                               1
Belarus                              154
Belgium                              276
Bermuda                                1
Bohemia                                5
Botswana                               2
Brazil                               184
British West Indies                    2
Bulgaria                             411
Burundi                                3
Cameroon                              12
Canada                               846
Chile                                 24
China                               1120
Colombia        

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [15]:
census_df = pd.read_csv('census.csv')
census_df

SUMLEV  REGION  DIVISION  STATE  COUNTY     STNAME             CTYNAME  \
0         40       3         6      1       0    Alabama             Alabama   
1         50       3         6      1       1    Alabama      Autauga County   
2         50       3         6      1       3    Alabama      Baldwin County   
3         50       3         6      1       5    Alabama      Barbour County   
4         50       3         6      1       7    Alabama         Bibb County   
5         50       3         6      1       9    Alabama       Blount County   
6         50       3         6      1      11    Alabama      Bullock County   
7         50       3         6      1      13    Alabama       Butler County   
8         50       3         6      1      15    Alabama      Calhoun County   
9         50       3         6      1      17    Alabama     Chambers County   
10        50       3         6      1      19    Alabama     Cherokee County   
11        50       3         6      1      21    Alabama      Chilton County   
12        50       3         6      1      23    Alabama      Choctaw County   
13        50       3         6      1      25    Alabama       Clarke County   
14        50       3         6      1      27    Alabama         Clay County   
15        50       3         6      1      29    Alabama     Cleburne County   
16        50       3         6      1      31    Alabama       Coffee County   
17        50       3         6      1      33    Alabama      Colbert County   
18        50       3         6      1      35    Alabama      Conecuh County   
19        50       3         6      1      37    Alabama        Coosa County   
20        50       3         6      1      39    Alabama    Covington County   
21        50       3         6      1      41    Alabama     Crenshaw County   
22        50       3         6      1      43    Alabama      Cullman County   
23        50       3         6      1      45    Alabama         Dale County   
24        50       3         6      1      47    Alabama       Dallas County   
25        50       3         6      1      49    Alabama       DeKalb County   
26        50       3         6      1      51    Alabama       Elmore County   
27        50       3         6      1      53    Alabama     Escambia County   
28        50       3         6      1      55    Alabama       Etowah County   
29        50       3         6      1      57    Alabama      Fayette County   
...      ...     ...       ...    ...     ...        ...                 ...   
3163      50       2         3     55     131  Wisconsin   Washington County   
3164      50       2         3     55     133  Wisconsin     Waukesha County   
3165      50       2         3     55     135  Wisconsin      Waupaca County   
3166      50       2         3     55     137  Wisconsin     Waushara County   
3167      50       2         3     55     139  Wisconsin    Winnebago County   
3168      50       2         3     55     141  Wisconsin         Wood County   
3169      40       4         8     56       0    Wyoming             Wyoming   
3170      50       4         8     56       1    Wyoming       Albany County   
3171      50       4         8     56       3    Wyoming     Big Horn County   
3172      50       4         8     56       5    Wyoming     Campbell County   
3173      50       4         8     56       7    Wyoming       Carbon County   
3174      50       4         8     56       9    Wyoming     Converse County   
3175      50       4         8     56      11    Wyoming        Crook County   
3176      50       4         8     56      13    Wyoming      Fremont County   
3177      50       4         8     56      15    Wyoming       Goshen County   
3178      50       4         8     56      17    Wyoming  Hot Springs County   
3179      50       4         8     56      19    Wyoming      Johnson County   
3180      50       4         8     56      21    Wyoming      Laramie County   
3181  

In [16]:
census_df['SUMLEV'].unique()

array([40, 50])

In [17]:
unique_counties = census_df[census_df['SUMLEV'] == 50].groupby('STNAME')['COUNTY'].nunique()  # use nunique() or count()
unique_counties

STNAME
Alabama                  67
Alaska                   29
Arizona                  15
Arkansas                 75
California               58
Colorado                 64
Connecticut               8
Delaware                  3
District of Columbia      1
Florida                  67
Georgia                 159
Hawaii                    5
Idaho                    44
Illinois                102
Indiana                  92
Iowa                     99
Kansas                  105
Kentucky                120
Louisiana                64
Maine                    16
Maryland                 24
Massachusetts            14
Michigan                 83
Minnesota                87
Mississippi              82
Missouri                115
Montana                  56
Nebraska                 93
Nevada                   17
New Hampshire            10
New Jersey               21
New Mexico               33
New York                 62
North Carolina          100
North Dakota             53
Ohio         

In [18]:
(census_df[census_df['SUMLEV'] == 50]).groupby(census_df['STNAME']).count().COUNTY

STNAME
Alabama                  67
Alaska                   29
Arizona                  15
Arkansas                 75
California               58
Colorado                 64
Connecticut               8
Delaware                  3
District of Columbia      1
Florida                  67
Georgia                 159
Hawaii                    5
Idaho                    44
Illinois                102
Indiana                  92
Iowa                     99
Kansas                  105
Kentucky                120
Louisiana                64
Maine                    16
Maryland                 24
Massachusetts            14
Michigan                 83
Minnesota                87
Mississippi              82
Missouri                115
Montana                  56
Nebraska                 93
Nevada                   17
New Hampshire            10
New Jersey               21
New Mexico               33
New York                 62
North Carolina          100
North Dakota             53
Ohio         

In [19]:
unique_counties = (census_df[census_df['SUMLEV'] == 50].groupby('STNAME')['COUNTY'].nunique()).idxmax()
unique_counties

'Texas'

In [20]:

census_df[(census_df['STATE'] == 1) & (census_df['COUNTY'] == 5)]

#census_df['STATE'].max()
#census_df['STATE'].count()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
3      50       3         6      1       5  Alabama  Barbour County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
3          27457              27457            27341     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
3         -4.728132          -2.50069         -7.056824         -3.904217   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   

   RNETMIG2015  
3   -10.543299  

[1 rows x 100 columns]

In [21]:
census_df['STATE'].count()

3193

In [22]:
census_df.shape

(3193, 100)

In [23]:
a = [census_df['STATE'].max(), census_df['STATE'].min()]
a

[56, 1]

In [24]:
def answer_five():
    return (census_df[census_df['SUMLEV'] == 50].groupby('STNAME')['COUNTY'].nunique()).idxmax()

answer_five()

'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [25]:
census_df[census_df['SUMLEV'] == 40].sort('CENSUS2010POP', ascending=False).head()

/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


SUMLEV  REGION  DIVISION  STATE  COUNTY      STNAME     CTYNAME  \
190       40       4         9      6       0  California  California   
2566      40       3         7     48       0       Texas       Texas   
1860      40       1         2     36       0    New York    New York   
329       40       3         5     12       0     Florida     Florida   
608       40       2         3     17       0    Illinois    Illinois   

      CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
190        37253956           37254503         37334079     ...        
2566       25145561           25146105         25244363     ...        
1860       19378102           19378087         19402920     ...        
329        18801310           18804623         18849890     ...        
608        12830632           12831549         12841249     ...        

      RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
190          -1.148464         -1.163788         -1.339869         -0.862856   
2566          4.527491          5.484904          4.446476          6.072953   
1860         -4.354557         -5.945385         -5.561401         -8.130297   
329           5.556307          5.138184          4.847420          6.958576   
608          -5.243330         -5.805172         -5.308960         -7.509147   

      RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
190          -1.981572     2.761704     2.647127     2.728645     3.743342   
2566          6.248252     7.616364     8.660719     7.739851     9.780487   
1860         -7.990563     1.439239    -0.402860     0.407960    -1.334639   
329          10.080932    11.364173    10.676030    10.565882    13.478570   
608          -8.174675    -3.020410    -3.519051    -2.830379    -4.625216   

      RNETMIG2015  
190      2.656065  
2566     9.978697  
1860    -1.205321  
329     16.528676  
608     -5.247030  

[5 rows x 100 columns]

In [26]:
Most_pop_state = census_df[census_df['SUMLEV'] == 40].sort('CENSUS2010POP', ascending=False).head(3)['STNAME']
type(Most_pop_state)

/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


pandas.core.series.Series

In [27]:
Most_pop_state

190     California
2566         Texas
1860      New York
Name: STNAME, dtype: object

In [28]:
list(Most_pop_state)

['California', 'Texas', 'New York']

In [29]:
Most_pop_state.apply(', '.join)

190     C, a, l, i, f, o, r, n, i, a
2566                   T, e, x, a, s
1860          N, e, w,  , Y, o, r, k
Name: STNAME, dtype: object

In [30]:
import itertools
list(itertools.chain.from_iterable(Most_pop_state.values))

['C',
 'a',
 'l',
 'i',
 'f',
 'o',
 'r',
 'n',
 'i',
 'a',
 'T',
 'e',
 'x',
 'a',
 's',
 'N',
 'e',
 'w',
 ' ',
 'Y',
 'o',
 'r',
 'k']

In [31]:
def answer_six():
    return list(census_df.sort('CENSUS2010POP', ascending=False).head(3)['STNAME'])

answer_six()

/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


['California', 'Texas', 'New York']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [32]:
pop_list = ['CTYNAME', 'POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015']
pop_df = census_df[census_df['SUMLEV'] == 50][pop_list]
pop_df.head()

CTYNAME  POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
1  Autauga County            54660            55253            55175   
2  Baldwin County           183193           186659           190396   
3  Barbour County            27341            27226            27159   
4     Bibb County            22861            22733            22642   
5   Blount County            57373            57711            57776   

   POPESTIMATE2013  POPESTIMATE2014  POPESTIMATE2015  
1            55038            55290            55347  
2           195126           199713           203709  
3            26973            26815            26489  
4            22512            22549            22583  
5            57734            57658            57673

In [33]:
pop_df['MAXPOP'] = pop_df.max(axis= 1) 
pop_df['MINPOP'] = pop_df.min(axis= 1)
pop_df['MAXCHNGPOP'] = pop_df['MAXPOP'] -pop_df['MINPOP']
pop_df.head()

CTYNAME  POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
1  Autauga County            54660            55253            55175   
2  Baldwin County           183193           186659           190396   
3  Barbour County            27341            27226            27159   
4     Bibb County            22861            22733            22642   
5   Blount County            57373            57711            57776   

   POPESTIMATE2013  POPESTIMATE2014  POPESTIMATE2015  MAXPOP  MINPOP  \
1            55038            55290            55347   55347   54660   
2           195126           199713           203709  203709  183193   
3            26973            26815            26489   27341   26489   
4            22512            22549            22583   22861   22512   
5            57734            57658            57673   57776   57373   

   MAXCHNGPOP  
1         687  
2       20516  
3         852  
4         349  
5         403

In [34]:
pop_df.shape

(3142, 10)

In [35]:
type(pop_df.loc[pop_df['MAXCHNGPOP'].idxmax()]['CTYNAME'])

str

In [36]:
pop_df.loc[pop_df['MAXCHNGPOP'].idxmax()]['CTYNAME']

'Harris County'

In [37]:
def answer_seven():
    list_pop = ['CTYNAME', 'POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015']
    pop1015_df = census_df[census_df['SUMLEV'] == 50][list_pop]
    pop1015_df['MAXCHNGPOP'] = pop1015_df.max(axis= 1) - pop1015_df.min(axis= 1)
    return pop1015_df.loc[pop1015_df['MAXCHNGPOP'].idxmax()]['CTYNAME']

answer_seven()

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [38]:
df_step1 = census_df[census_df['SUMLEV'] == 50][census_df['REGION'] < 3][census_df['POPESTIMATE2015'] > census_df['POPESTIMATE2014']]
df_out = df_step1[['STNAME','CTYNAME']]
df_out[df_out['CTYNAME'].str.contains('Washington')]  # df_out[df_out['CTYNAME'] == 'Washington County']

/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if __name__ == '__main__':


STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [39]:
def answer_eight():
    df_step1 = census_df[census_df['SUMLEV'] == 50][census_df['REGION'] < 3][census_df['POPESTIMATE2015'] > census_df['POPESTIMATE2014']]
    df_out = df_step1[['STNAME','CTYNAME']]
    return df_out[df_out['CTYNAME'].str.contains('Washington')]

answer_eight()

/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  from ipykernel import kernelapp as app


STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County